app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('netflix/',netflix,name='netflix'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('login/',login,name='login')
]

projectJ_GUN/urls.py
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('second/',second,name='second'),
]

projectJ_SPU/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('register/',register,name='register'),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.


def first(request):
    return render(request,'first.html')

def second(request):
    return render(request,'second.html')

app1/views.py
from django.shortcuts import render

# Create your views here.

def netflix(request):
    return render(request,'netflix.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

app3/views.py
from django.shortcuts import render

# Create your views here.

def register(request):
    return render(request,'register.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        div
        {
            width: 600px;
        }
    </style>
</head>
<body>
    <center>
        <h1>This is for generic url naviagtion purpose</h1>
        <div>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis dicta enim consequatur facilis nesciunt. Provident, asperiores vel beatae ex eos similique quidem veritatis qui aspernatur numquam incidunt, nostrum dolore suscipit consequatur mollitia, iste quaerat cum optio nam! Sint repudiandae repellat animi eius commodi possimus tempore. Ut impedit quis ullam voluptates illum consequatur dolores aliquid voluptatibus aperiam ratione, deserunt sint quod possimus officia? Ipsum culpa minus aspernatur illum a, dicta ex tenetur perspiciatis temporibus nihil aut dolore molestias at soluta pariatur ullam, perferendis fuga ea delectus vitae quia. Voluptates possimus tempora atque commodi exercitationem numquam, nisi harum sint nesciunt similique consequatur sapiente deserunt aliquam sed perferendis molestias accusamus pariatur reiciendis. Odio, quaerat placeat voluptatem nostrum repellat accusamus nobis aperiam ducimus in corrupti inventore totam itaque ullam provident mollitia eligendi dolore minima qui. Dignissimos tenetur excepturi deleniti possimus in eum, assumenda illum dolorem debitis placeat quos quisquam ex iste. Maxime, ducimus. Ad similique necessitatibus perspiciatis voluptas sequi corrupti voluptatum, ipsum, eligendi officiis, odit a consectetur ducimus cupiditate maiores vel quibusdam voluptatem error aut. Corrupti reiciendis eveniet asperiores atque sunt numquam maxime inventore nisi laborum aliquam dolorem perspiciatis sed nulla fugiat corporis commodi soluta, alias minima ut quaerat iusto optio ad amet labore.</p>
        </div>

        <h1><a href="{% url 'second' %}">Click here</a> to go to second app</h1>
    </center>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>To login to the <i><b>Netflix</b></i> you to take subscription</h1>
        <h1>Before subscription you have to create an account in Netflix</h1>
        <h1>So kindly register yourself in int Netflix and follow the necessary steps to complete the process</h1>
        <h1>If you don't have an account go to register page</h1>
        <a href="{% url 'register' %}"><h2>Click here to go to register form</h2></a>
    </center>
</body>
</html>

templates/netflix.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h2>This is the main page for <i><b>-Netflix-</b></i></h2>
        <p>Lorem ipsum dolor sit amet consectetur, 
           adipisicing elit. Voluptatibus sit, quo possimus quae eum 
           officiis nobis quis odit ipsam culpa? Corporis corrupti quos
           autem repellat iure quis eligendi dicta eum pariatur officia ducimus 
           quia, cupiditate repellendus sit minus saepe aliquam? Non incidunt 
           dolorum porro, rem laborum facere esse voluptatum at.
        </p>
        <h1>If you have an account go to log in page</h1>
        <a href="{% url 'app2:login' %}"><h2>Click here to go to login page</h2></a>

    </center>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        div
        {
            background-color: aqua;
            text-align: center;
            color: red;
        }
        i
        {
            color: black;
        }
    </style>
</head>
<body>
    <center>
        <h1>To Register to the Netflix you have to follow the instructions and do</h1>
        <div>
            <i><h3>Instructions</h3></i>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
                Laboriosam eos officiis ratione corrupti magni alias 
                totam illo quasi nam <br>
                Lorem, ipsum dolor sit amet consectetur adipisicing 
                elit. Non placeat illo sequi fuga, reprehenderit in 
                porro aliquam nisi inventore unde repellendus repellat 
                <br>
                numquam dignissimos, explicabo, cumque excepturi a
                spernatur illum exercitationem eius? Expedita vitae omnis 
                quis earum veritatis sed officiis, debitis ex fugit laudantium 
                temporibus molestiae qui quaerat perspiciatis. Totam, fuga?
            </p>
        </div>
        <h1>If you already have an account go back to Netflix page</h1>

        <a href="{% url 'app1:netflix' %}"><h2>lick here to go to Netflix page</h2></a>
    </center>
</body>
</html>